workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      groups:
        - test

    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
          echo keyAlias=$CM_KEY_ALIAS >> $"$CM_BUILD_DIR/android/local.properties"
          echo keyPassword=$CM_KEY_PASSWORD >> $"$CM_BUILD_DIR/android/local.properties"
          echo storePassword=$CM_KEYSTORE_PASSWORD >> $"$CM_BUILD_DIR/android/local.properties"
          cat $"$CM_BUILD_DIR/android/local.properties"
          echo $LOL

      #   - name: Get Flutter packages
      #     script: |
      #       flutter packages pub get
      #   - name: Build AAB with Flutter
      #     script: |
      #       flutter build apk --release
      # artifacts:
      #   - build/**/outputs/**/*.aab
      #   - build/**/outputs/**/mapping.txt
      #   - flutter_drive.log

    # publishing:
    #   email:
    #     recipients:
    #       - user_1@example.com
    #       - user_2@example.com
    #     notify:
    #       success: true
    #       failure: false
    #   google_play:
    #     credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
    #     track: $GOOGLE_PLAY_TRACK
    #     submit_as_draft: true
