name: Android Release

on:
  #   push:
  #     branches: [ "master" ]
  #   pull_request:
  #     branches: [ "master" ]

  workflow_dispatch:

env:
  JAVA_VERSION: "11.x"
  FLUTTER_VERSION: "3.10.0"
  FLUTTER_CHANNEL: "stable"
  PROPERTIES_PATH: "./android/key.properties"
  KEY_PATH: "./android/upload.jks"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: ${{JAVA_VERSION}}
          cache: "gradle"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{FLUTTER_VERSION}}
          channel: ${{FLUTTER_CHANNEL}}
          cache: true

      - name: Resolve dependencies
        run: flutter pub get

      - name: Analyze Code
        run: flutter analyze

      - name: Create Signing Key Secrets
        run: |
          echo keyAlias=${{secrets.KEY_ALIAS}} > ${{PROPERTIES_PATH}}
          echo keyPassword=${{secrets.KEY_PASS}} >> ${{PROPERTIES_PATH}}
          echo storePassword=${{secrets.KEY_STORE_PASS}} >> ${{PROPERTIES_PATH}}

      - name: Decode Signing Key
        run: echo '${{secrets.KEY}}' | base64 --decode > ${{KEY_PATH}}

      - name: Build APK
        run: flutter build apk --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/flutter-apk/app-release.apk
